# This file was generated by GoReleaser. DO NOT EDIT.
cask "stacksenv" do
  version "1.0.12"

  desc "CLI for managing your Environment Variables"
  homepage "https://github.com/stacksenv/cli"

  on_macos do
    on_intel do
      url "https://github.com/stacksenv/cli/releases/download/v#{version}/darwin-amd64-stacksenv.tar.gz"
      sha256 "07bc4badd5095b5823f89e4a2621639d827ef94722642aecbbdde18fc60e4293"
    end
    on_arm do
      url "https://github.com/stacksenv/cli/releases/download/v#{version}/darwin-arm64-stacksenv.tar.gz"
      sha256 "3b6cbf07494cbcbb237a7f7ca9e22da8f8246fc81a12c5eebd622d501a06e1f2"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/stacksenv/cli/releases/download/v#{version}/linux-amd64-stacksenv.tar.gz"
      sha256 "f0dd152a242dd588fb16ee82b6f14b42d4c0bdad7d0b1d9606e0bdf6b46f8584"
    end
    on_arm do
      url "https://github.com/stacksenv/cli/releases/download/v#{version}/linux-arm64-stacksenv.tar.gz"
      sha256 "5d5f0ab3f69c03c34181f3b1370905d86a0b49910c8cc580558faac752e1d782"
    end
  end

  binary "stacksenv"

  livecheck do
    skip "Auto-generated on release."
  end

  postflight do
    if system_command("/usr/bin/xattr", args: ["-h"]).exit_status.zero?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/stacksenv"]
    end
  end

  # No zap stanza required
end
