# This file was generated by GoReleaser. DO NOT EDIT.
cask "stacksenv" do
  name "stacksenv"
  desc "Stacksenv is a CLI for managing your Environment Variables"
  homepage "https://github.com/stacksenv/cli"
  version "1.0.13"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "stacksenv"

  on_macos do
    on_intel do
      url "https://github.com/stacksenv/cli/releases/download/v#{version}/darwin-amd64-stacksenv.tar.gz"
      sha256 "212c6fa4889078d5cad591aea2d7d8c81d18d44bd2c30e03254e72a8233cc6a2"
    end
    on_arm do
      url "https://github.com/stacksenv/cli/releases/download/v#{version}/darwin-arm64-stacksenv.tar.gz"
      sha256 "5fe1ede0eab3a26f4968026e5863c85282525d16b5a0af9f8c55d29e96931226"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/stacksenv/cli/releases/download/v#{version}/linux-amd64-stacksenv.tar.gz"
      sha256 "cc966ddfd59945dbe00df0e1b6058842503f15195c8f33956fcfd457a2468f06"
    end
    on_arm do
      url "https://github.com/stacksenv/cli/releases/download/v#{version}/linux-arm64-stacksenv.tar.gz"
      sha256 "c38c8d458f73dd2ea42074ad23e214cf25dfbef1fb1b2cff0d784dc43c10cfc0"
    end
  end

  postflight do
    if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/stacksenv"]
    end
  end

  # No zap stanza required
end
