# This file was generated by GoReleaser. DO NOT EDIT.
cask "stacksenv" do
  name "stacksenv"
  desc "Stacksenv is a CLI for managing your Environment Variables"
  homepage "https://github.com/stacksenv/cli"
  version "1.0.9"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "stacksenv"

  on_macos do
    on_intel do
      url "https://github.com/stacksenv/cli/releases/download/v#{version}/darwin-amd64-stacksenv.tar.gz"
      sha256 "4332e297497e6e988c7d002e01771e943a0525f94b153797c42cce27c1e1dcab"
    end
    on_arm do
      url "https://github.com/stacksenv/cli/releases/download/v#{version}/darwin-arm64-stacksenv.tar.gz"
      sha256 "c7d590cb2f815774fca700e82fb4da51232b16765427887ef56a97a5713fe79e"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/stacksenv/cli/releases/download/v#{version}/linux-amd64-stacksenv.tar.gz"
      sha256 "892fcc05da66f0aa74c9a0fd2eeac71654c15b5013354a4cd03459a91721f841"
    end
    on_arm do
      url "https://github.com/stacksenv/cli/releases/download/v#{version}/linux-arm64-stacksenv.tar.gz"
      sha256 "2b9c1375d2d5a8a9adabb7793925e4e6d262a60c47c7ee9a1ab6ce46723e7115"
    end
  end

  postflight do
    if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/stacksenv"]
    end
  end



  def install
    bin.install "stacksenv"
  end

  test do
    system "#{bin}/stacksenv", "--version"
  end
  # No zap stanza required
end
